Add "Copy to clipboard" button
canonical-webteam/example-js pull request #32
Opened 2018-06-04 13:08 UTC by Caleb-Ellis

## Done

- Added a "Copy to clipboard" button to rendered code examples
- Gave each of the code block elements classnames, so they're easier to target with stylesheets:
  - `.p-code-example`
  - `.p-code-example__code`
  - `.p-code-example__copy-btn`
- Updated `testing.html` with current Vanilla codeblock and button styling
- Added 4px top/bottom padding to iframes so that focused inputs don't get cropped

## QA

- Pull code
- Run `npm run build`
- Run `npm run start`
- Open http://127.0.0.1:8080/testing/
- Check there is a copy to clipboard button in the top right of codeblocks
- Check that clicking it copies the codeblock to clipboard properly (e.g. paste to a text editor and see that it matches)

## Fixes

Fixes #30, fixes #22, fixes https://github.com/vanilla-framework/vanilla-framework/issues/1436

2018-06-04 13:28 UTC, anthonydillon requested changes
@Caleb-Ellis Can you depend on Vanilla framework and only include the patterns you require like how the cookie policy used the notification pattern.

2018-06-04 13:29 UTC, anthonydillon commented
https://github.com/canonical-webteam/cookie-policy/blob/master/src/sass/cookie-policy.scss

2018-06-04 14:22 UTC, Caleb-Ellis commented
@anthonydillon Done. Also I opted to include inline styles on the `pre` and `button` so all we theoretically need to do to update Vanilla docs is update the example.js version number. Thoughts?

2018-06-06 12:50 UTC, anthonydillon requested changes
Few questions on the code.

2018-06-06 12:50 UTC, anthonydillon commented on js/example.js
> +  document.execCommand("copy");
I think you need a try catch here to stop a console error and allow you to provide a useful console.warning.

2018-06-06 12:50 UTC, anthonydillon commented on package.json
> +    "build-css": "node-sass --include-path node_modules scss --output css",
Shouldn't the CSS go into the build directory too?

2018-06-06 12:50 UTC, anthonydillon commented on scss/styles.scss
> +@include vf-b-button;
Can we not include the copy to clipboard icon from vanilla instead are adding it inline.

2018-06-06 14:27 UTC, Caleb-Ellis commented
@anthonydillon Did the fixes you suggested.

2018-06-07 10:04 UTC, anthonydillon commented
There is no indication you have copied the text field. Could use a tooltip or a highlight background on the input. 

The clipboard icon doesn't display on Firefox.

2018-06-07 10:35 UTC, Caleb-Ellis commented
@anthonydillon Fixed the firefox issue and created an issue in Vanilla about it (https://github.com/vanilla-framework/vanilla-framework/issues/1856).
The copy text indicator is also an issue here https://github.com/vanilla-framework/vanilla-framework/issues/1632 - I'll fix it in Vanilla once a design has been approved and pull the update in here.

2018-06-07 11:35 UTC, anthonydillon approved these changes

2018-06-07 11:36 UTC, merged